# Generated by Django 3.2.9 on 2025-04-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='incoming_call_from',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
