# Generated by Django 3.2.9 on 2025-04-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_incoming_call_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='in_call_with',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_girl',
            field=models.BooleanField(default=False),
        ),
    ]
