# Generated by Django 5.2 on 2025-04-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
