# Generated by Django 5.2 on 2025-04-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_call_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_busy',
            field=models.BooleanField(default=False),
        ),
    ]
