# Generated by Django 5.2 on 2025-05-02 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_kyc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='pan_card_image',
        ),
        migrations.AddField(
            model_name='kyc',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
