# Generated by Django 5.2 on 2025-05-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_wallet_coins_remove_wallet_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='earnings_coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
