# Generated by Django 5.2 on 2025-05-05 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_wallet_earnings_coins_wallet_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='in_call_with',
        ),
    ]
