# Generated by Django 5.2 on 2025-05-05 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_user_in_call_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='in_call_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_partner', to=settings.AUTH_USER_MODEL),
        ),
    ]
