# Generated by Django 5.2 on 2025-06-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_callhistory_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawaltransaction',
            name='tds_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
