# Generated by Django 5.2 on 2025-06-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='mutual_connected_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
