# Generated by Django 5.2 on 2025-06-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_kyc_mobile_number_kyc_pan_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='pan_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
