# Generated by Django 5.2 on 2025-11-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='kyc_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
