name: Deploy to Fly.io

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'  # 🚀 Enables pip cache

      - name: Ensure pip cache dir exists
        run: mkdir -p ~/.cache/pip  # ✅ Fix for pip cache warning

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Try Deploying with Multiple Volumes
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          volumes=("pg_data_try4" "pg_data_try3" "pg_data_retry" "pg_data_new")

          for vol in "${volumes[@]}"; do
            echo "🔁 Trying volume: $vol"
            sed -i "s/source = \".*\"/source = \"$vol\"/" fly.toml

            if flyctl deploy --remote-only; then
              echo "✅ Successfully deployed using volume: $vol"
              exit 0
            else
              echo "❌ Failed with volume: $vol, trying next..."
            fi
          done

          echo "🚨 All volume attempts failed"
          exit 1
